### ISSUE TITLE
RemovedConnectionAlerts could not be started

### ISSUE THREAD

**Issue by jack652** [iyu46/RemovedConnectionAlerts#14]
![image](https://github.com/iyu46/RemovedConnectionAlerts/assets/48365199/0c7dde4f-2466-4f72-bfe8-c132cb7c5b8e)

**Comment by BloodGozilla** [comment]
having the same isse

**Comment by BloodGozilla** [comment]
Fixed the issue by deleting all config files for RemovedConnectionAlert and then redownloading it.

**Comment by iyu46** [comment]
I believe this is addressed here https://github.com/iyu46/RemovedConnectionAlerts/issues/6#issuecomment-1805244138
