### ISSUE TITLE
Icon is missing

### ISSUE THREAD

**Issue by goreyard** [iyu46/RemovedConnectionAlerts#20]
The icon to pull the list up without the need to manually open it from the plugins settings is not there.
![image](https://github.com/iyu46/RemovedConnectionAlerts/assets/112436994/1fe92413-8d3d-469c-837c-72c0f115636a)
^not there

**Comment by iyu46** [comment]
In this case usually toggling the plugin off and on in the settings will fix it. This happens sometimes when discord is annoying.
