### ISSUE TITLE
File is invalid for import when trying to import metalloriff's history file

### ISSUE THREAD

**Issue by Music1984** [iyu46/RemovedConnectionAlerts#24]
title, though when i change the name to have my id i get a different error (backup failed)

**Comment by iyu46** [comment]
Can you share the error that appears in the console when you try to import your history? Would you also be comfortable sharing that old history file?

**Comment by Music1984** [comment]
![image](https://github.com/iyu46/RemovedConnectionAlerts/assets/98255301/5a7f08be-cfe0-49d9-955e-2650853dfeaa)
Do you have a discord i can send the history file to?

**Comment by Music1984** [comment]
mb sorry didn't mean to close it

**Comment by iyu46** [comment]
Absolutely! You can add me at "selia."
