### ISSUE TITLE
Icon profile not showing

### ISSUE THREAD

**Issue by TheOppaiDragon** [iyu46/RemovedConnectionAlerts#25]
Hello i have a problem where if i go to removed list i see some friend in the list don't load the pfp image in the plugin. There is any fix?

![Progetto senza titolo](https://github.com/iyu46/RemovedConnectionAlerts/assets/29179424/602f12f6-b862-4f6c-a74c-b0c1adea4cd8)

**Comment by iyu46** [comment]
This is unfortunately inevitable, because I don't want to store icons on every user's computer. The icons are stored on Discord's side, and they get regularly deleted after a certain amount of time.
