### ISSUE TITLE
Error pops up when i launch discord / start plugin manually

### ISSUE THREAD

**Issue by DanTVD** [iyu46/RemovedConnectionAlerts#27]
so i had this msg appear today after i opened discord..
the history file is completely intact tho and not corrupted and even when i delete / remove the file named under my uid it still says it is corrupted...

anyone has any idea if it is a bug that needs to be fixed soon by the dev or something of sorts? or is there a solution?

![image](https://github.com/user-attachments/assets/7fcca10a-c6b2-41b8-8f42-76e576aabf21)

**Comment by Czerwony150** [comment]
Probably because of this discord reloads every few minutes.

**Comment by CompletelyUnbelievable** [comment]
As far as I can tell the problem is that ZerePluginLibrary's GuildStore.getGuilds no longer exists for some reason, causing something I would consider to be a bug that it is informing the user that the history is somehow corrupt when it's just unable to access the user's guild info.
![image](https://github.com/user-attachments/assets/78068b60-84ac-467c-a9fd-4015b11aebda)
![image](https://github.com/user-attachments/assets/913df978-d9c1-4e17-901b-327021256964)

**Comment by iyu46** [comment]
omg i'm sorry!! i'll look into this right away i was sleeping hlksdfds

**Comment by CompletelyUnbelievable** [comment]
> omg i'm sorry!! i'll look into this right away i was sleeping hlksdfds

I wouldn't worry too much about it since it seems to be a ZLib issue. It would be a good idea to do something so that you know for sure the history is corrupt before telling the user that it is. Parsing the error message might be a good idea, or you could try/catching either or both of the `getGuildsList` or the function for loading the config, to present a proper error message.

**Comment by CompletelyUnbelievable** [comment]
Before:
https://github.com/iyu46/RemovedConnectionAlerts/blob/8e08ad10f31dbcec8339672fe8a55361cba51c55/RemovedConnectionAlerts.plugin.js#L161-L163
The temporary fix I'm using for now and afaik it's working properly:
```javascript
const {
        React, Dispatcher, RelationshipStore, UserStore,
    } = DiscordModules;
	var { GuildStore } = DiscordModules;
	if(!GuildStore.getGuilds)GuildStore=BdApi.findModuleByProps('getGuilds', 'getGuild');
```

**Comment by iyu46** [comment]
okay, sent in a fix! i'll update the thread again when it's approved and available for everyone to download, but you should get a ping on the built in updater anyway!

**Comment by Thiago3246** [comment]
bro for me automatic update for this plugin dont worked now with this last fix

**Comment by iyu46** [comment]
> bro for me automatic update for this plugin dont worked now with this last fix

@Thiago3246 that's because it's not available in the automatic update system yet, be patient :D

**Comment by iyu46** [comment]
it should be available for auto-update now!!

**Comment by Sharkcruiser** [comment]
Hey,
just wanted to say that I am still getting the popup.
It did not auto update for me so I removed it, except the history files and downloaded it again from the betterdiscord page, its working again but the popup about corrupted files still shows up everytime I restart discord

**Comment by iyu46** [comment]
> Hey, just wanted to say that I am still getting the popup. It did not auto update for me so I removed it, except the history files and downloaded it again from the betterdiscord page, its working again but the popup about corrupted files still shows up everytime I restart discord

@Sharkcruiser can you tell me, if you open your current history file (`RemovedConnectionAlerts_(number).config.json`) in notepad, if you see any text or if its just empty?

**Comment by Sharkcruiser** [comment]
> > Hey, just wanted to say that I am still getting the popup. It did not auto update for me so I removed it, except the history files and downloaded it again from the betterdiscord page, its working again but the popup about corrupted files still shows up everytime I restart discord
> 
> @Sharkcruiser can you tell me, if you open your current history file (`RemovedConnectionAlerts_(number).config.json`) in notepad, if you see any text or if its just empty?

There is text in it, its not empty
The Plugin also shows normally at the top right and I can open it and see my history
Its just the popup message that still shows up on every start

**Comment by iyu46** [comment]
> > > Hey, just wanted to say that I am still getting the popup. It did not auto update for me so I removed it, except the history files and downloaded it again from the betterdiscord page, its working again but the popup about corrupted files still shows up everytime I restart discord
> > 
> > 
> > @Sharkcruiser can you tell me, if you open your current history file (`RemovedConnectionAlerts_(number).config.json`) in notepad, if you see any text or if its just empty?
> 
> There is text in it, its not empty The Plugin also shows normally at the top right and I can open it and see my history Its just the popup message that still shows up on every start

i see... if you check the plugin's version inside discord settings, is it 0.8.5? can you tell me if there's an error in the console after you open the plugin?

and would you be willing to share your history file with me? if you are, you can add me on discord at `selia.` and send it to me privately that way

**Comment by Sharkcruiser** [comment]
> > > > Hey, just wanted to say that I am still getting the popup. It did not auto update for me so I removed it, except the history files and downloaded it again from the betterdiscord page, its working again but the popup about corrupted files still shows up everytime I restart discord
> > > 
> > > 
> > > @Sharkcruiser can you tell me, if you open your current history file (`RemovedConnectionAlerts_(number).config.json`) in notepad, if you see any text or if its just empty?
> > 
> > 
> > There is text in it, its not empty The Plugin also shows normally at the top right and I can open it and see my history Its just the popup message that still shows up on every start
> 
> i see... if you check the plugin's version inside discord settings, is it 0.8.5? can you tell me if there's an error in the console after you open the plugin?
> 
> and would you be willing to share your history file with me? if you are, you can add me on discord at `selia.` and send it to me privately that way

It actually shows me 0.8.3 as Version
Not sure why, as I deleted the old ones and downloaded the new one which said updated today

I can share the file with you no problem, but not sure what selia is :D

**Comment by iyu46** [comment]
> It actually shows me 0.8.3 as Version

well that must be why! I imagine it's not updated yet on the site's side. you could wait a bit until "check for updates" works on your discord client, or you could manually replace the plugin with the updated version by downloading this github repository as an archive (https://github.com/iyu46/RemovedConnectionAlerts/archive/refs/heads/main.zip), picking out the plugin.js file, and replacing the one in your plugins folder with it (you can delete the archive after)
