### ISSUE TITLE
plugin bugs out when u switch to an alt

### ISSUE THREAD

**Issue by Legenerate** [iyu46/RemovedConnectionAlerts#4]
the plugin thinks you removed all of the friends that aren't added on your alt and the cache gets f"cked. all of these are my friends on my main, when i switched back to my main, it still shows that they're all removed??
![image](https://user-images.githubusercontent.com/76908360/222372866-080b6672-e799-492e-b0de-8ba130d2e3a6.png)

**Comment by iyu46** [comment]
Oh! I see the problem, I think - it didn't do this before in my testing, but I guess something changed to where it became problematic.

I'm so sorry for the inconvenience! I hope your original cache is okay - I'm not sure if you can recover it if it isn't in this case, and I'm sincerely sorry for any data lost with this problem. I'll look into fixing this soon! In the meantime, could you try disabling the plugin when you swap to your alt, if you don't need it there?

**Comment by iyu46** [comment]
I submitted an update for this. It will take a little while for the update to be approved for the automatic BD plugin patcher, but in the meantime if you'd like to redownload the plugin from this repository you're welcome to. It should load in as version 0.6.3.

**Comment by Legenerate** [comment]
> 

yeah i just manually deleted all of the extra removals lol, and thanks plus okie

**Comment by iyu46** [comment]
0.6.3 is available through the auto-updater, and should fix this problem!
