### ISSUE TITLE
Scrolling stops before end of list is reached

### ISSUE THREAD

**Issue by amadeusjustinn** [iyu46/RemovedConnectionAlerts#7]
When I open the modal and scroll, the scrolling stops before I reached either the top or bottom of the list. I had to stop and then restart scrolling.
I am using Discord Canary 0.0.295 on macOS Ventura 13.2.1.

**Comment by iyu46** [comment]
Are you able to give me a recording of this, or alternatively are you still able to reproduce this problem?

**Comment by amadeusjustinn** [comment]
@iyu46 Yes, of course:

https://user-images.githubusercontent.com/67861264/229332086-f9cf92f4-ff9b-4331-ba4a-c0307b574e0b.mov

Here, I've scrolled continuously with my trackpad, and the scrolling pauses just before I run out of room on the trackpad. That stop was not due to my letting go of my fingers off the trackpad, it just behaves like that.

**Comment by iyu46** [comment]
Hi I figured this out I think lol. Sorry it took a year but I think I addressed the problem in this upcoming hotfix
